package presentacion;

import database.Conexion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author steff
 */
public class FrmGraficaVenta extends javax.swing.JInternalFrame {

    ArrayList<String> fechas = new ArrayList<>();
    ArrayList<Integer> compras = new ArrayList<>();
    ArrayList<Integer> ventas = new ArrayList<>();

    public FrmGraficaVenta() {
        initComponents();
        setSize(new Dimension(800, 600));
        setTitle("Gráfico de Compras y Ventas");
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        cargarDatos();

        PanelGrafica panelGrafica = new PanelGrafica(fechas, compras, ventas);
        JScrollPane scrollPane = new JScrollPane(panelGrafica);
        scrollPane.setPreferredSize(new Dimension(780, 550));

        panelPrincipal.setLayout(new java.awt.BorderLayout());
        panelPrincipal.add(scrollPane, java.awt.BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Graficas");

        jLabel1.setText("Súper Grafica");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel1)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatos() {
        try (Connection cn = Conexion.getInstancia().conectar()) {
            String sql = "SELECT fecha, tipo_transaccion, COUNT(*) as total FROM transaccion "
                    + "WHERE fecha BETWEEN ? AND ? GROUP BY fecha, tipo_transaccion";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, FrmRegistrosVentas.fecha_inicio);
            pst.setString(2, FrmRegistrosVentas.fecha_fin);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String fecha = rs.getString("fecha");
                String tipo = rs.getString("tipo_transaccion");
                int total = rs.getInt("total");

                if (!fechas.contains(fecha)) {
                    fechas.add(fecha);
                    compras.add(0);
                    ventas.add(0);
                }

                int index = fechas.indexOf(fecha);
                if ("compra".equalsIgnoreCase(tipo)) {
                    compras.set(index, total);
                } else if ("venta".equalsIgnoreCase(tipo)) {
                    ventas.set(index, total);
                }
            }

        } catch (Exception e) {
            System.out.println("Error al cargar datos: " + e.getMessage());
        }
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
